spring.application.name=OtelApp1

#otel.exporter.otlp.endpoint=
#otel.serviceName=

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
logging.level.io.opentelemetry=DEBUG
logging.level.io.micrometer.tracing=DEBUG

logging.level.root=DEBUG
management.tracing.sampling.probability=1.0